---
platform: linux
image: docker:///concourse/static-golang

inputs:
  - name: time-resource
    path: gopath/src/github.com/concourse/time-resource

run:
  path: gopath/src/github.com/concourse/time-resource/scripts/ci
